### ISSUE TITLE
Improved or additional generated content

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#32]
- [x] details about production process like contraction grade
- [x] if notes are present and where to find them (see https://github.com/joeha480/dotify/issues/200)
- [x] how tables are rendered: it is still unclear what exactly needs to be generated based on what (blocked on: https://github.com/snaekobbi/pipeline-mod-nlb/issues/34)
- [x] total number of braille pages/sheets contained in the current volume/book (see https://github.com/joeha480/dotify/issues/198)

For a more detailed description of the expected output ask @KariRudjord.

**Comment by bertfrees** [comment]
Information about notes should include whether they are placed at the bottom of pages or at the end of the volume, if the fallback mechanism has been used.

**Comment by bertfrees** [comment]
@usama49 How is it going for the first item ("details about production process like contraction grade")? Have you managed to get it working?

**Comment by usama49** [comment]
i tested but it is not working as expected, may be XProc script / XSLT are not passing  parameter to boilplater.xsl. I will talk to @josteinaj  today and fix this issue and let you know.

**Comment by bertfrees** [comment]
I should be able to help you with it as well. Is there a unit test maybe?

**Comment by usama49** [comment]
I have updated git-hub (ammar branch) with test that fails. it should pass if it is getting variable from XProc script / XSLT.
on page three   output generated content is  incorrect  `<row>⠀⠀⠀⠀⠀⠀⠀⠠⠋⠥⠇⠇⠎⠅⠗⠊⠋⠞</row>`
output should be

``` xml
<row>⠀⠀⠀⠀⠀⠀⠀⠠⠅⠕⠗⠞⠎⠅⠗⠊⠋⠞⠀⠝⠊⠧⠡⠀</row>
<row>⠀⠀⠀⠀⠀⠼⠁</row>
```

@bertfrees can you have a look at it when you have time.
Thanks

**Comment by bertfrees** [comment]
OK there was a bug in pre-processing.xpl. Jostein did something funny with the parameters. Pushed a fix. Tests pass now.

**Comment by usama49** [comment]
Hi @bertfrees ,
I am trying to add sheets in volume and document using CSS but it fails and I receive error.
`Java.lang.NumberFormatException: For input string: "$sheets-in-document" </error>`

I am using following css.

``` css
.volume {
   display: inline;
}   
.volume::after  {
   display: inline;                                
   content: -obfl-evaluate('(round $sheets-in-document)')  ;  
}   
```

I am pushing it to mod-nlb ammar branch. It would be nice if you have look when you have time.
Thanks

**Comment by bertfrees** [comment]
OK I'll have a look.

**Comment by bertfrees** [comment]
@usama49 I have merged 1.8.1 into your branch. Now the error says: `java.lang.NumberFormatException: For input string: "null"`. The problem is that the `p` with class "volume" is not flowed in a `@begin` or `@end` area, which is required for the evaluation of "$sheets-in-document".

It works after I add the rule `.second-page, .third-page { flow: front; }` however I'm not sure that is what's desired, so I'll leave that to you.

There are also some failing tests and one test with an error `Failed to complete volume division.`. I don't whether these were issues before or not?

**Comment by usama49** [comment]
@bertfrees 
thanks for help.I tried this CSS

```

.second-page , .third-page  {   flow: front;        } 
.pages  {display: inline;   }   
.pages::after   {   display: inline;                                
content:    -obfl-evaluate('(round $sheets-in-document)')  ;    }   

```

and it is working fine but  error `Failed to complete volume division..` issue occurs. 

when I disable  CSS this particular test works fine.
https://github.com/snaekobbi/pipeline-mod-nlb/blob/ammar/src/test/xprocspec/test_dtbook-to-pef.xprocspec#L450
Have you any Idea ?

Other thing is that we don't need 2nd and 3rd page before each volume.(only first page is needed before each volume). If we use `flow: front`  for 2nd or 3rd page, will it produce these pages for each volume?

(I have pushed it to mod-nlb ammar branch)
Thanks

**Comment by bertfrees** [comment]
> Other thing is that we don't need 2nd and 3rd page before each volume.(only first page is needed before each volume). If we use `flow: front`  for 2nd or 3rd page, will it produce these pages for each volume?

Yes, that is what I was unsure about. Just use a different flow for the 2nd and 3rd page then, which you include in the first volume only (with `@volume:first {...}`)

I've looked a bit closer at your test that causes the "Failed to complete volume division" error. It has the rule `@volume { max-length: 2; }` in it. 2 is really not much, try increasing that a bit.

**Comment by usama49** [comment]
@bertfrees 
Test is working when I increased `max-length`.  
The problem now is that 2nd and 3rd page repeats in each volume. I tried to fix it with CSS but no success.I tried this CSS

```

@volume:first {
            .second-page , .third-page
                 {flow: front;  } 
                }

.pages{ display: inline;    }           
.pages::after   {
        display: inline;                                
        content:    -obfl-evaluate('(round $sheets-in-document)')  ;    }

```

and this also

```
@volume:first 
    {
        .second-page , .third-page
            {
                flow: front;        
            } 

        .pages
            {
                display: inline;        
            }           
        .pages::after
            {
                display: inline;                                
                content:    -obfl-evaluate('(round $sheets-in-document)')  ;                
            } 
    }
```

Any Idea?
Thanks

**Comment by bertfrees** [comment]
``` css
.second-page , .third-page {
   flow: front-first;
}
@volume:first {
   @begin {
      content: flow(front-first) flow(front)
   }
}
```

**Comment by usama49** [comment]
@bertfrees 
Thanks  it works fine with little changes.
I have finished pages in generated content and CSS improvements. Can you please merge ammar branch.
thanks

**Comment by josteinaj** [comment]
Great. I'll merge the ammar branch into v1.9-dev first, I think there's some changes there as well.

**Comment by josteinaj** [comment]
@usama49 will test with `$pages-in-document` instead of `$sheets-in-document`.

**Comment by bertfrees** [comment]
`pages-in-document` is not supported. But OK, a test helps not forgetting.

**Comment by josteinaj** [comment]
Ok. If it's not supported then maybe we can just use a variable with `$sheets-in-document * 2` in SCSS instead? We'd be fine with that as well.

**Comment by bertfrees** [comment]
OK, yes, that's the easiest solution right now I think.

**Comment by josteinaj** [comment]
@usama49 you'll try creating a variable with the value `$sheets-in-document * 2` (rounding etc. as needed, don't know the syntax) ?

**Comment by usama49** [comment]
@bertfrees  
I tried to get number of pages from sheets. using `-obfl-evaluate('(round $sheets-in-document)') * 2`. but it is causing error 
`Could not compile SASS style sheet: Error: Undefined operation: "-obfl-evaluate("(round $sheets-in-document)") times 2". on line 42 of bundle://13.0:1/css/nlb-default.scss >> $sheets-in-document: -obfl-evaluate('(round $sheets-in-document)') * 2 ; ---------------------^`
Any Guess?
Thanks.

**Comment by bertfrees** [comment]
http://braillespecs.github.io/obfl/obfl-evaluation-language.html

**Comment by josteinaj** [comment]
@usama49: we marked this as "done". Is that right? Can we close this issue?

**Comment by usama49** [comment]
done, please close it.

**Comment by josteinaj** [comment]
Great
